version: '3.8'

services:
  auth-server:
    build: ./app
    container_name: gpt-proxy-auth
    restart: unless-stopped
    mem_limit: 64m
    cpus: "0.2"

  nginx:
    image: nginx:latest
    container_name: gpt-proxy-nginx
    ports:
      - "8080:2280"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-server
    restart: unless-stopped
    mem_limit: 32m
    cpus: "0.2"
